config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/mattiaBarbo/SQAaaS_Test:
      branch: main
      repo: https://github.com/mattiaBarbo/SQAaaS_Test.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/mattiaBarbo/SQAaaS_Test git:
        commands:
        - /usr/bin/env sh .sqa/script.ready-ochre-tarsier.sh
        container: qc.acc_cranky-platinum-dodo
  QC.Doc:
    repos:
      github.com/mattiaBarbo/SQAaaS_Test find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-champagne-moose.sh
        container: qc.doc_skimpy-sapphire-dachshund
      github.com/mattiaBarbo/SQAaaS_Test git:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-purple-bear.sh
        container: qc.doc_smelly-lavender-tortoise
      github.com/mattiaBarbo/SQAaaS_Test markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-charcoal-flounder.sh
        container: qc.doc_droopy-peach-cow
  QC.Lic:
    repos:
      github.com/mattiaBarbo/SQAaaS_Test licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-yellow-akita.sh
        container: qc.lic_woozy-gold-dollar
  QC.Sec:
    repos:
      github.com/mattiaBarbo/SQAaaS_Test bandit:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-burgundy-dragonfly.sh
        container: qc.sec_thirsty-teal-millipede
  QC.Sty:
    repos:
      github.com/mattiaBarbo/SQAaaS_Test flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-pink-owl.sh
        container: qc.sty_lanky-dandelion-affenpinscher
      github.com/mattiaBarbo/SQAaaS_Test hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.randy-copper-wolverine.sh
        container: qc.sty_fuzzy-magnolia-burmese
  QC.Uni:
    repos:
      github.com/mattiaBarbo/SQAaaS_Test commands:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-apricot-moorhen.sh
        container: qc.uni_slimy-coral-worm
  QC.Ver:
    repos:
      github.com/mattiaBarbo/SQAaaS_Test get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-ecru-cougar.sh
        container: qc.ver_scummy-copper-dalmatian
timeout: 5400
